name: main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize]
  pull_request_target:
    branches:
      - 'main'
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event_name == 'push' ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'pull_request' ||
        (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))
      }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: check with Gradle
        run: ./gradlew checkstyle --info
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PARDOT_JAVA_CLIENT_READ_TOKEN }}
      - name: build with Gradle
        run: ./gradlew build --info
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PARDOT_JAVA_CLIENT_READ_TOKEN }}

  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [ test ]
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew gem --info
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PARDOT_JAVA_CLIENT_READ_TOKEN }}
      - name: Push gem
        uses: trocco-io/push-gem-to-gpr-action@v1
        with:
          language: java
          gem-path: "./build/gems/*.gem"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
